version: '3.9'
services:
  app:
    container_name: next_wa_app
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/node/home/app
    command: npm run dev
    ports:
      - 3000:3000

